---

name: Cypress Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List Files and Folders
        run: |
          pwd
          ls -R  

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Check Node.js and NPM Version
        run: |
          node -v
          npm -v
        
      - name: Install Dependencie
        run: |
          npm i
          
      - name: Run Cypress Test
        run: npm run cypress:run
      
      - name: Install Allure CLI
        run: npm install -g allure-commandline --save-dev

      - name: Check Allure Installation
        run: allure --version

      - name: Generate Allure Report
        run: |
          allure generate ./allure-results --clean -o ./allure-report

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-report  


  deploy:
    name: Deploy GitHub Pages
    runs-on: ubuntu-latest
    if: always()
    needs: test
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://juliana-souza-franca.github.io/develop-api-cypress/report.html
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: ./allure-report  

      - name: Upload Allure Report to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./allure-report 

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
