---

name: Cypress Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List Directory (Debugging Step)
        run: ls -R  

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
        
      - name: Install Dependencies
        working-directory: CYPRESS_API  
        run: |
          npm install
          npm install cypress
          npm install --save-dev @shelex/cypress-allure-plugin
          npm install --save-dev allure-commandline
        
      - name: Run Cypress Tests
        env:
          baseUrl: 'https://develop.qacoders.dev.br/'
        working-directory: CYPRESS_API 
        run: npm run cypress:run

      - name: Generate Allure Report
        working-directory: CYPRESS_API  
        run: |
          npm run allure:generate
          allure generate ./allure-results --clean -o ./allure-report

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: CYPRESS_API/allure-report  

  deploy:
    name: Deploy GitHub Pages
    runs-on: ubuntu-latest
    if: always()
    needs: test
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://juliana-souza-franca.github.io/develop-api-cypress/report.html
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: CYPRESS_API/allure-report  

      - name: Upload Allure Report to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: CYPRESS_API/allure-report 

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
